modLoader = "javafml"
loaderVersion = "[33,)"
license = "Code: LGPLv3 \nAssets: All Rights Reserved"
issueTrackerURL = "https://github.com/CorgiTaco/BYG/issues"
[[mods]]
modId = "byg"
version = "1.1.10"
displayName = "Oh The Biomes You'll Go"
displayURL = "https://oh-the-biomes-youll-go.fandom.com/wiki/Oh_The_Biomes_You%27ll_Go_Wiki"
logoFile = "logo_text.png"
credits = "On curse"
authors = "AOCAWOL & Corgi Taco"
description = '''
An Adventure and Exploration mod with over 60 new biomes!

Notice: The linked wiki is not owned by BYG, the wiki is open for anyone to edit and any inaccuracies that may appear are not BYG's responsibility.
'''
[[dependencies.byg]]
modId = "forge"
mandatory = true
versionRange = "[36.0.4,)"
ordering = "NONE"
side = "BOTH"